# Generated by Django 3.0.8 on 2020-07-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='colour',
            field=models.CharField(default='#079d41', max_length=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
