# Generated by Django 3.0.8 on 2020-08-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='colour',
            field=models.CharField(default='#676767', max_length=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='colour',
            field=models.CharField(default='#079d41', max_length=21),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
